from tkinter import *
import sqlite3
from tkinter import messagebox
root = Tk()
def close_window ():
    root.destroy()
def generate():
    conn = sqlite3.connect('adv.db')
    c = conn.cursor()
    id1 = enn.get()
    paws = enn1.get()
    password = c.execute('SELECT password FROM signup WHERE id = ? ', (id1,))
    pass1 = password.fetchone()[0]
    if (paws == pass1):
        label98 = Label(root,text="Enter graph Id").grid(row=5,column=1)
        label66 = Label(root, text="X range").grid(row=6, column=1)
        label67 = Label(root, text="Y range").grid(row=7, column=1)
        label68 = Label(root, text="Enter divisions").grid(row=8, column=1)
        er1.grid(row=5, column=2)
        en1.grid(row=6, column=2)
        en2.grid(row=7, column=2)
        en3.grid(row=8, column=2)
        label = Label(root, text="X1 AND Y1 COORDINATE").grid(row=9, column=1)
        label = Label(root, text="X2 AND Y2 COORDINATE").grid(row=10, column=1)
        label = Label(root, text="X3 AND Y3 COORDINATE").grid(row=11, column=1)
        label = Label(root, text="X4 AND Y4 COORDINATE").grid(row=12, column=1)
        label = Label(root, text="X5 AND Y5 COORDINATE").grid(row=13, column=1)
        en4.grid(row=9, column=2)
        en5.grid(row=10, column=2)
        en6.grid(row=11, column=2)
        en7.grid(row=12, column=2)
        en8.grid(row=13, column=2)
        en9.grid(row=9, column=3)
        en10.grid(row=10, column=3)
        en11.grid(row=11, column=3)
        en12.grid(row=12, column=3)
        en13.grid(row=13, column=3)
        w = Button(root, text='Next', command=callback).grid(row=14, column=1)
        w1 = Button(root, text='Quit', command=close_window).grid(row=14, column=2)
    else:
        messagebox.showinfo("Error","Invalid Info")
        root.destroy()

def callback():
    conn = sqlite3.connect('adv.db')
    c = conn.cursor()
    gra = er1.get()
    idd = enn.get()
    xran = en1.get()
    yran = en2.get()
    div = en3.get()
    x1 = en4.get()
    y1 = en5.get()
    x2 = en6.get()
    y2 = en7.get()
    x3 = en8.get()
    y3 = en9.get()
    x4 = en10.get()
    y4 = en11.get()
    x5 = en12.get()
    y5 = en13.get()
    c.execute("CREATE TABLE IF NOT EXISTS coordinate(id INT,graph INT, xrange INT, yrange INT, div INT, x1 INT, y1 INT, x2 INT, y2 INT, x3 INT, y3 INT, x4 INT, y4 INT, x5 INT, y5 INT)")
    c.execute('INSERT INTO coordinate(id,graph, xrange, yrange, div, x1, y1, x2, y2, x3, y3, x4, y4, x5, y5) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', (idd,gra, xran, yran, div, x1, y1, x2, y2, x3, y3, x4, y4, x5, y5))
    conn.commit()
    c.close()
    conn.close()
    messagebox.showinfo("Message","Successfull")
    root.destroy()
label = Label(root,text=" ").grid(row=9,column=1)
llo = Label(root,text="Store values").grid(row=1,column=5)
label = Label(root,text="Enter id").grid(row=2,column=1)
enn = Entry(root)
enn.grid(row=2,column=2)
labe = Label(root,text="Enter password").grid(row=3,column=1)
enn1 = Entry(root)
enn1.config(show="#")
enn1.grid(row=3,column=2)
w=Button(root,text='Verify',command=generate).grid(row=4,column=2)
er1 = Entry(root)
en1 = Entry(root)
en2 = Entry(root)
en3 = Entry(root)
en4 = Entry(root)
en5 = Entry(root)
en6 = Entry(root)
en7 = Entry(root)
en8 = Entry(root)
en9 = Entry(root)
en10 = Entry(root)
en11 = Entry(root)
en12 = Entry(root)
en13 = Entry(root)
root.mainloop()