from tkinter import *
import sqlite3
from tkinter import messagebox
root = Tk()
def close_window ():
    root.destroy()
def callback():
    idd = e14.get()
    name = e11.get()
    user = e12.get()
    passw = e13.get()
    conn = sqlite3.connect('adv.db')
    c = conn.cursor()
    c.execute("CREATE TABLE IF NOT EXISTS signup(id INT,name, username,password)")
    c.execute('INSERT INTO signup (id ,name, username, password)VALUES (?, ?, ?, ?)', (idd,name, user, passw))
    messagebox.showinfo("Mesage", "Signup Successfull")
    conn.commit()
    c.close()
    conn.close()
label = Label( root,text="Graph Genertor Login Page",font=("Helvetica", 16))
label.grid(row=0,column=5)
label = Label(root,text="")
label.grid(row=3,column=1)
label = Label( root,text="SIGN UP",font=("Helvetica", 16))
label.grid(row=6,column=5)
label15 = Label(root,text="Id").grid(row=7,column=1)
label2 = Label(root,text="Name")
label2.grid(row=8,column=1)
label3 = Label(root,text="Username")
label3.grid(row=9,column=1)
label4 = Label(root,text="Password")
label4.grid(row=10,column=1)
e11 = Entry(root)
e12 = Entry(root)
e13 = Entry(root)
e14 = Entry(root)
e13.config(show="#")
e11.grid(row=8,column=2)
e12.grid(row=9,column=2)
e13.grid(row=10,column=2)
e14.grid(row=7,column=2)
label = Label(root,text=" ")
label.grid(row=11,column=3)
w=Button(root,text='Quit',command=close_window)
w.grid(row=12,column=1)
w=Button(root,text='Signup',command=callback)
w.grid(row=12,column=2)
root.mainloop()